### ISSUE TITLE
intake-solr is missing in pypi

### ISSUE THREAD

**Issue by sodre** [ContinuumIO/intake-solr#6]
@martindurant, would it be possible to upload intake-solr to pypi?

**Comment by martindurant** [comment]
Done. It ought to have a conda-forge entry too, though.
[This page](https://intake.github.io/status/) shows progress with uploading the various drivers to pypi and conda-forge (and removing from the intake conda channel)

**Comment by sodre** [comment]
Thank you! I see it is available now! Now that page makes more sense to me!
